name: media_match
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  path: ^1.9.0
  record: ^4.4.4
  lottie: ^2.7.0
  lordicon: ^1.0.3
  image_picker: ^1.1.2
  audioplayers: ^5.2.1
  path_provider: ^2.1.3
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  awesome_snackbar_content: ^0.1.3
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ThinItalic.ttf

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/animation/
